skillchains = {
    [288] = {id=288,en='Light (Thunder)',index=6},
    [289] = {id=289,en='Darkness (Ice)',index=5},
    [290] = {id=290,en='Grav. (Earth)',index=2},
    [291] = {id=291,en='Frag. (Thunder)',index=6},
    [292] = {id=292,en='Dist. (Ice)',index=5},
    [293] = {id=293,en='Fusion (Fire)',index=1},
    [294] = {id=294,en='Compr.',index=nil},
    [295] = {id=295,en='Liquef. (Fire)',index=1},
    [296] = {id=296,en='Indur. (Ice)',index=5},
    [297] = {id=297,en='Reverb. (Water)',index=3},
    [298] = {id=298,en='Transf.', index=nil},
    [299] = {id=299,en='Scis. (Earth)', index=2},
    [300] = {id=300,en='Deton. (Wind)', index=4},
    [301] = {id=301,en='Impac. (Thunder)', index=6}
}

elements = T{"fire","earth","water","wind","ice","thunder","light","dark"}

spells = {
    fire = {
        index = 1,
        color = "\\cs(255,22,12)",
        nuke = {"Fire","Fire II","Fire III","Fire IV","Fire V","Fire VI"},
        nukega = {"Firaga","Firaga II","Firaga III","Firaja"},
        nukera = {"Fira","Fira II","Fira III"},
        ancient = {"Flare","Flare II"},
        helix = {"Pyrohelix","Pyrohelix II"},
        storm = {"Firestorm","Firestorm II"},
        chain = {"Stone","Fire"},
    },
    earth = {
        index = 2,
        color = "\\cs(255,255,28)",
        nuke = {"Stone","Stone II","Stone III","Stone IV","Stone V","Stone VI"},
        nukega = {"Stonega","Stonega II","Stonega III","Stoneja"},
        nukera = {"Stonera","Stonera II","Stonera III"},
        ancient = {"Quake","Quake II"},
        helix = {"Geohelix","Geohelix II"},
        storm = {"Sandstorm","Sandstorm II"},
        chain = {"Fire","Stone"},
    },
    water = {
        index = 3,
        color = "\\cs(0,150,255)",
        nuke = {"Water","Water II","Water III","Water IV","Water V","Water VI"},
        nukega = {"Waterga","Waterga II","Waterga III","Waterja"},
        nukera = {"Watera","Watera II","Watera III"},
        ancient = {"Flood","Flood II"},
        helix = {"Hydrohelix","Hydrohelix II"},
        storm = {"Rainstorm","Rainstorm II"},
        chain = {"Stone","Water"},
    },
    wind = {
        index = 4,
        color = "\\cs(51,255,20)",
        nuke = {"Aero","Aero II","Aero III","Aero IV","Aero V","Aero VI"},
        nukega = {"Aeroga","Aeroga II","Aeroga III","Aeroja"},
        nukera = {"Aerora","Aerora II","Aerora III"},
        ancient = {"Tornado","Tornado II"},
        helix = {"Anemohelix","Anemohelix II"},
        storm = {"Windstorm","Windstorm II"},
        chain = {"Stone","Aero"},
    },
    ice = {
        index = 5,
        color = "\\cs(0,255,255)",
        nuke = {"Blizzard","Blizzard II","Blizzard III","Blizzard IV","Blizzard V","Blizzard VI"},
        nukega = {"Blizzaga","Blizzaga II","Blizzaga III","Blizzaja"},
        nukera = {"Blizzara","Blizzara II","Blizzara III"},
        ancient = {"Freeze","Freeze II"},
        helix = {"Cryohelix","Cryohelix II"},
        storm = {"Hailstorm","Hailstorm II"},
        chain = {"Water","Blizzard"},
    },
    thunder = {
        index = 6,
        color = "\\cs(233,0,255)",
        nuke = {"Thunder","Thunder II","Thunder III","Thunder IV","Thunder V","Thunder VI"},
        nukega = {"Thundaga","Thundaga II","Thundaga III","Thundaja"},
        nukera = {"Thundara","Thundara II","Thundara III"},
        ancient = {"Burst","Burst II"},
        helix = {"Ionohelix","Ionohelix II"},
        storm = {"Thunderstorm","Thunderstorm II"},
        chain = {"Water","Thunder"},
    },
    light = {
        index = 7,
        color = "\\cs(255,255,255)",
        nuke = {"Thunder","Thunder II","Thunder III","Thunder IV","Thunder V","Thunder VI"},
        nukega = {"Thundaga","Thundaga II","Thundaga III","Thundaja"},
        nukera = {"Thundara","Thundara II","Thundara III"},
        ancient = {"Burst","Burst II"},
        helix = {"Luminohelix","Luminohelix II"},
        storm = {"Aurorastorm","Aurorastorm II"},
        chain = {"Fire","Thunder"},
    },
    dark = {
        index = 8,
        color = "\\cs(135,135,135)",
        nuke = {"Blizzard","Blizzard II","Blizzard III","Blizzard IV","Blizzard V","Blizzard VI"},
        nukega = {"Blizzaga","Blizzaga II","Blizzaga III","Blizzaja"},
        nukera = {"Blizzara","Blizzara II","Blizzara III"},
        ancient = {"Freeze","Freeze II"},
        helix = {"Noctohelix","Noctohelix II"},
        storm = {"Umbrastorm","Umbrastorm II"},
        chain = {"Aero","Noctohelix"},
    },
}

return {
    skillchains = skillchains,
    elements = elements,
    spells = spells,
}
